
const PDFDocument = require("pdfkit");
const { Document, Packer, Paragraph, TextRun, AlignmentType, BorderStyle } = require("docx");
exports.generatePDF = async (req, res) => {
  try {
    const data = req.body;

    if (!data || typeof data !== "object") {
      return res.status(400).json({ error: "Invalid resume data" });
    }

    const doc = new PDFDocument({
      margin: 50,
      size: "A4"
    });
    const chunks = [];

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", 'attachment; filename="resume.pdf"');

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => res.send(Buffer.concat(chunks)));

    // ===== HEADER =====
    doc.fontSize(22).text(data.name || "Your Name", { align: "center", underline: true });
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor("gray")
      .text(
        [data.email, data.phone, data.linkedin].filter(Boolean).join(" | "),
        { align: "center" }
      );
    doc.moveDown(1);

    const addSeparator = () => {
      const y = doc.y + 3;
      doc.moveTo(50, y).lineTo(550, y).strokeColor("#cccccc").lineWidth(0.5).stroke();
      doc.moveDown(0.5);
    };

    const addSection = (title) => {
      doc.fontSize(13).fillColor("#003366").text(title, { underline: true });
      addSeparator();
      doc.fillColor("black").fontSize(11);
      doc.moveDown(0.2);
    };

    const addLineSpacing = () => doc.moveDown(0.3);

    // ===== PROFESSIONAL SUMMARY =====
    addSection("PROFESSIONAL SUMMARY");
    doc.text(data.professional_summary || "N/A", { lineGap: 2 });
    addLineSpacing();

    // ===== EDUCATION =====
    addSection("EDUCATION");
    (data.education || []).forEach((edu) => {
      doc.text(`${edu.institution} — ${edu.area || ""} • ${edu.score || ""}`, { lineGap: 2 });
      addLineSpacing();
    });

    // ===== SKILLS =====
    addSection("SKILLS");
    if (Array.isArray(data.skills) && data.skills.length > 0) {
      const skillText = data.skills
        .map((s) => (s.keywords ? s.keywords.join(" • ") : s))
        .join(" • ");
      doc.text(skillText, { lineGap: 2 });
    } else {
      doc.text("N/A");
    }
    addLineSpacing();

    // ===== EXPERIENCE =====
    addSection("EXPERIENCE");
    (data.experience || []).forEach((ex) => {
      doc.font("Helvetica-Bold").text(`${ex.role} — ${ex.company}`, { lineGap: 2 });
      doc.font("Helvetica");
      (ex.summary || []).forEach((line) => doc.text(`• ${line}`, { lineGap: 2 }));
      addLineSpacing();
    });

    // ===== PROJECTS =====
    addSection("PROJECTS");
    (data.projects || []).forEach((p) => {
      doc.font("Helvetica-Bold").text(p.name, { lineGap: 2 });
      doc.font("Helvetica").text(p.description, { lineGap: 2 });
      addLineSpacing();
    });

    // ===== ACHIEVEMENTS =====
    addSection("ACHIEVEMENTS");
    (data.achievements || []).forEach((a) => {
      doc.text(`• ${a}`, { lineGap: 2 });
    });

    // ===== FOOTER =====
    doc.moveDown(1);
    const footerY = doc.page.height - 50;
    doc.fontSize(9).fillColor("gray")
      .text("Generated by ResumeCraft AI • © 2025", 50, footerY, { align: "center", width: 500 });

    doc.end();
  } catch (err) {
    console.error("✗ PDF generation error:", err);
    res.status(500).json({ error: "Failed to generate PDF" });
  }
};



exports.generateDOCX = async (req, res) => {
  try {
    const data = req.body;

    if (!data || typeof data !== "object") {
      return res.status(400).json({ error: "Invalid resume data" });
    }

    const doc = new Document({
      sections: [
        {
          properties: {
            page: {
              margin: { top: 720, bottom: 720, left: 720, right: 720 }, // 0.5" margins
            },
          },
          children: [
            // === HEADER ===
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [
                new TextRun({ text: data.name || "No Name", bold: true, size: 32 }),
              ],
            }),
            new Paragraph({
              alignment: AlignmentType.CENTER,
              spacing: { after: 200 },
              children: [
                new TextRun({
                  text: [data.email, data.phone, data.linkedin]
                    .filter(Boolean)
                    .join(" | "),
                  size: 20,
                  color: "555555",
                }),
              ],
            }),

            // === PROFESSIONAL SUMMARY ===
            ...createSection("Professional Summary", data.professional_summary),

            // === EDUCATION ===
            ...createSection(
              "Education",
              (data.education || []).map(
                (e) =>
                  `${e.institution || ""} — ${e.studyType || ""} (${e.area || ""}) ${
                    e.score ? "• " + e.score : ""
                  }`
              )
            ),

            // === SKILLS ===
            ...createSection(
              "Skills",
              (data.skills || []).map((s) =>
                `${s.category || ""}: ${(s.keywords || []).join(", ")}`
              )
            ),

            // === EXPERIENCE ===
            ...createSection(
              "Experience",
              (data.experience || []).map(
                (ex) =>
                  `${ex.role || ""} at ${ex.company || ""}\n${(ex.summary || [])
                    .map((line) => "• " + line)
                    .join("\n")}`
              )
            ),

            // === PROJECTS ===
            ...createSection(
              "Projects",
              (data.projects || []).map(
                (p) => `${p.name || ""}: ${p.description || ""}`
              )
            ),

            // === ACHIEVEMENTS ===
            ...createSection(
              "Achievements",
              (data.achievements || []).map((a) => "• " + a)
            ),

            // === FOOTER ===
            new Paragraph({
              alignment: AlignmentType.CENTER,
              spacing: { before: 400 },
              children: [
                new TextRun({
                  text: "Generated by ResumeCraft",
                  italics: true,
                  size: 18,
                  color: "999999",
                }),
              ],
            }),
          ],
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);
    res.setHeader("Content-Disposition", 'attachment; filename="resume.docx"');
    res.setHeader(
      "Content-Type",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    );
    res.send(buffer);
  } catch (err) {
    console.error("✗ DOCX generation error:", err);
    res.status(500).json({ error: "Failed to generate DOCX" });
  }
};

// === Section Helper Function ===
function createSection(title, lines) {
  if (!lines || (Array.isArray(lines) && lines.length === 0)) return [];

  const section = [
    new Paragraph({
      text: title,
      spacing: { before: 200, after: 100 },
      bold: true,
      border: {
        bottom: { color: "999999", size: 6, style: BorderStyle.SINGLE },
      },
    }),
  ];

  if (typeof lines === "string") {
    section.push(
      new Paragraph({
        text: lines,
        spacing: { after: 100 },
        lineSpacing: { after: 120 },
      })
    );
  } else if (Array.isArray(lines)) {
    lines.forEach((line) => {
      section.push(
        new Paragraph({
          text: line,
          spacing: { after: 80 },
          lineSpacing: { after: 120 },
        })
      );
    });
  }
  return section;
}
